# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(439, 224)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWhatsThis("")
        MainWindow.setIconSize(QtCore.QSize(250, 5))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(50, 20, 347, 121))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.cbxExchange = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbxExchange.setObjectName("cbxExchange")
        self.cbxExchange.addItem("")
        self.cbxExchange.addItem("")
        self.cbxExchange.addItem("")
        self.gridLayout.addWidget(self.cbxExchange, 1, 1, 1, 1)
        self.tbxAmount = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.tbxAmount.setText("")
        self.tbxAmount.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tbxAmount.setObjectName("tbxAmount")
        self.gridLayout.addWidget(self.tbxAmount, 1, 0, 1, 1)
        self.cbxBuy = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.cbxBuy.setObjectName("cbxBuy")
        self.cbxBuy.addItem("")
        self.cbxBuy.addItem("")
        self.cbxBuy.addItem("")
        self.gridLayout.addWidget(self.cbxBuy, 1, 3, 1, 1)
        self.btnCalculate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnCalculate.setObjectName("btnCalculate")
        self.gridLayout.addWidget(self.btnCalculate, 2, 3, 1, 1)
        self.lblTo = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblTo.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblTo.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTo.setObjectName("lblTo")
        self.gridLayout.addWidget(self.lblTo, 1, 2, 1, 1)
        self.lblMiktar = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblMiktar.setAlignment(QtCore.Qt.AlignCenter)
        self.lblMiktar.setObjectName("lblMiktar")
        self.gridLayout.addWidget(self.lblMiktar, 0, 0, 1, 1)
        self.lblResult = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblResult.setText("")
        self.lblResult.setObjectName("lblResult")
        self.gridLayout.addWidget(self.lblResult, 4, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 150, 147, 23))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Anlık Döviz Hesaplayıcı"))
        self.cbxExchange.setItemText(0, _translate("MainWindow", "USD"))
        self.cbxExchange.setItemText(1, _translate("MainWindow", "EUR"))
        self.cbxExchange.setItemText(2, _translate("MainWindow", "TRY"))
        self.cbxBuy.setItemText(0, _translate("MainWindow", "TRY"))
        self.cbxBuy.setItemText(1, _translate("MainWindow", "USD"))
        self.cbxBuy.setItemText(2, _translate("MainWindow", "EUR"))
        self.btnCalculate.setText(_translate("MainWindow", "Hesapla"))
        self.lblTo.setText(_translate("MainWindow", "to"))
        self.lblMiktar.setText(_translate("MainWindow", "Miktar"))
        self.label.setText(_translate("MainWindow", "Developed by Deniz Varıcı"))
